config/routes.rb
Rails.application.routes.draw do
  get 'dashboard', to: "dashboard#show"
  root to: 'pages#home'
  devise_for :users
  resources :therapists, only: [:index, :show] do
    get 'update_main_therapist', to: 'therapists#update_main_therapist', as: 'assign_me'
    resources :bookings, only: [:new, :create, :edit, :update, :destroy] do
      get 'assign', to: 'pages#assign'
      get 'video_session', to: 'pages#video_session'
    end
    resources :reviews, only: [:new, :create]
  end
  resources :bookings, only: :show
  get 'sandbox', to: 'pages#sandbox'
  get 'welcome', to: 'pages#welcome'
  resources :bookings, only: :show do
    get 'video_session', to: 'pages#video_session'
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  skip_after_action :verify_authorized

  def show
    @user = current_user
    if !@user.therapist_id.nil?
      @user_therapist = Therapist.find(@user.therapist_id)
    end
    if @user.therapist_id
      @user_therapist = Therapist.find(@user.therapist_id)
    else
      @user_therapist = nil
    end
    @bookings = current_user.bookings
    @next_booking = @bookings.where("starts_at > ? and status <> ?", Date.today, 3)
    @today_booking = Booking
    .where(["starts_at = ? and status <> ?", Date.today, 3])
    .last
    # this bit of code is supposed to display the next booking you book in the future, if none is scheduled for today. but, it doesn't work reliably
    # if @today_booking.blank?
    #   @today_booking = @next_booking.last
    # end
    past_bookings = @bookings.where(["starts_at < ? or status = ? ", Date.today, 3])
    past_bookings = past_bookings.order(starts_at: :desc)
    @past_bookings = past_bookings.order(updated_at: :desc)
    @my_reviews = Review.where(user: current_user)
    if current_user.therapist_id
      @my_therapist = Therapist.find(current_user.therapist_id)
    end
  end
end

app/views/dashboard/show.html.erb
<div class="dashboard-container d-flex flex-column">

  <% if @user_therapist %>
  <div class="assigned d-flex flex-column justify-content-center py-3 mb-5">
 <div class="content-wrap d-flex px-5 relative">
      <%= link_to therapist_path(@user_therapist) do %>
   <%= cl_image_tag @user_therapist.photo, width: 140, class: "avatar-small mb-3 ab-photo" %>
   <% end %>
   <div class="flex-2">
     <h4>Your assigned therapist is <%=
       @user_therapist.first_name %> <%= @user_therapist.last_name %></h4>
       <% if @user_therapist %>
       <%= link_to therapist_path(@user_therapist) do %>
       <div class="white-button">
         Book now
       </div>
       <% end %>
       <% else %>
       <%= link_to therapists_path do %>
       <div class="white-button">
         Book now
       </div>
       <% end %>

       <% end %>
     </div>
 </div>
  </div>
  <% else %>
    <div class="assigned d-flex flex-column justify-content-center mb-5">
      <div class="content-wrap d-flex px-5 mb-5 pt-5">
      <div class="avatar-small mb-3" id="no-therapist">
      </div>
    <div class="flex-2">
      <h3 class="white-text">You don't have an assigned therapist yet !</h3>
        <%= link_to therapists_path do %>
        <div class="white-button" id="dash">
          Find one now
        </div>
        <% end %>
    </div>
  </div>
  </div>

  <% end %>


<h3 id="upcoming-header">Upcoming Appointments</h3>
  <% if @today_booking %>
    <div class="today border padded-box d-flex mb-5 relative m-80">
      <div class="calendar mr-4">
          <p id="date"> <%= @today_booking.starts_at.strftime("%d") %> </p>
          <i class="far fa-calendar" aria-hidden="true"></i>
        </div>
        <div class="calendar-date pl-3 flex-grow">
          <h3 class="mb-3 today-date"> <%= @today_booking.starts_at.strftime("%A, %d %B") %> at <%= @today_booking.time.strftime("%H:%M")%></h3>
          <%= link_to  therapist_booking_video_session_path(@today_booking.therapist, @today_booking), class: "d-flex flex-column align-items-center" do %>
            <i class="fas fa-video mb-3" aria-hidden="true"></i>
            <% end %>
        </div>
        <div class="d-flex flex-column justify-content-center align-items-center">
        <h7 id="badge-name">Dr. <%= @today_booking.therapist.first_name %> <%= @today_booking.therapist.last_name %> </h7>
          <%= link_to therapist_path(@today_booking.therapist) do %>
          <%= cl_image_tag @today_booking.therapist.photo, width: 140, class: "avatar-small" %>
          <% end %>
          </div>


        </div>
    <% else %>
    <div class="empty border padded-box mb-5 m-80">
      <p>You have no upcoming appointments. When you schedule one, the call button will be displayed here.</p>
    </div>
  <% end %>
  <h3 id="past-header">Past Appointments</h3>
  <% if !@past_bookings.blank? %>
    <div class="past padded-box m-80 mb-5">
     <%= render partial: "shared/past_bookings", past_bookings: @past_bookings %>
    </div>
 <%  %>
  <% else %>
    <div class="empty border padded-box mb-5 m-80">
      <p>You have not completed any sessions. When you have, you will be able to access them here.</p>
    </div>
<% end %>

</div>
</div>
    </div>



    <%#= link_to 'Add to Calendar', edit_therapist_booking_path(@today_booking.therapist, @today_booking), class: "calendar-button d-flex mx-2" %>