config/routes.rb
Rails.application.routes.draw do
  get 'dashboard', to: "dashboard#show"
  root to: 'pages#home'
  devise_for :users
  resources :therapists, only: [:index, :show] do
    get 'update_main_therapist', to: 'therapists#update_main_therapist', as: 'assign_me'
    resources :bookings, only: [:new, :create, :edit, :update, :destroy] do
      get 'assign', to: 'pages#assign'
      get 'video_session', to: 'pages#video_session'
    end
    resources :reviews, only: [:new, :create]
  end
  resources :bookings, only: :show
  get 'sandbox', to: 'pages#sandbox'
  get 'welcome', to: 'pages#welcome'
  resources :bookings, only: :show do
    get 'video_session', to: 'pages#video_session'
  end

end

app/views/shared/_bookings.html.erb
<div class="upcoming-booking border">
  <% @bookings.each do |booking|  %>

  <h3>Date <%= l(booking.starts_at, format: :long) %> </h3>

  <div class="d-flex flex-column mb-3">
    <%# Avatar row %>
    <div class="p-2 flex-fill border">
      <div class="booking-therapist-avatar d-flex align-items-center justify-content-center">
        <%= cl_image_tag booking.therapist.photo, width: 140, class: "avatar-small" %>
      </div>
    </div>
    <div class="p-2 flex-fill border">Flex item 2</div>

    <%# Button row %>
    <div class="p-2 flex-fill border">
      <!-- Replace with button_to for actual submit -->
      <div>
        <%= button_tag "Reschedule" %>
      </div>
      <div>
        <%= button_tag "Cancel" %>
      </div>
    </div>
  </div>

</div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
 <div class="footer">
     <p> If you are in a life threatening situation - don’t use this site. Call x to get immediate help. </p>
</div>

app/views/shared/_navbar.html.erb
<nav class=<%= params[:controller] == "pages" && params[:action] == "home" ? "transparent-nav" : "normal-nav" %>>
  <%= link_to 'iWell', root_path, id: "logo" %>
  <% if user_signed_in? %>
    <%= link_to "Log out", destroy_user_session_path, id: "#", method: "delete" %>
    <%= link_to "My account", edit_user_registration_path, id: "#" %>
    <%= link_to "My bookings", dashboard_path, id: "#" %>
  <% else %>
      <%= link_to "Join as a therapist", id: "#" %>
      <%= link_to "Login", new_user_session_path, id: "#" %>
    </li>
  <% end %>
</nav>

app/views/shared/_past_bookings.html.erb
<% @past_bookings.each do |booking| %>
  <div class="past-booking-card d-flex">
    <div class="avatar-box mr-4">
      <%= link_to therapist_path(booking.therapist) do %>
      <%= cl_image_tag booking.therapist.photo, class: "avatar-small-dashboard mb-3" %>
      <% end %>
    </div>

    <div class="past-info d-flex flex-column justify-content-around ml-5">
     <div class="flex-1 d-flex flex-column justify-content-between">
      <div class="info">
        <h5> <%= booking.starts_at.strftime("%A, %d %B") %>
           at <%= booking.time.strftime("%H:%M")%>
        </h5>
         <% if booking.free %>
         <h6> 15 Minute consultation </h6>
         <% else %>
         <h6> 60 Minute Session</h6>
         <% end %>
         <h6>with Dr. <%= booking.therapist.first_name %> <%= booking.therapist.last_name %> </h6>
        </div>
      </div>
      <div class="button-container d-flex justify-content-between mt-2">
        <% therapist = booking.therapist %>
        <% if @user_therapist != therapist %>
        <%= link_to therapist_assign_me_path(therapist) do %>
        <div class="">
          Assign as my therapist
        </div>
        <% end %>
        <% end %>
        <% reviewed = @my_reviews.where(therapist: therapist) %>
        <% if reviewed.blank? %>
        <a href="#" id="line">|</a>
        <%= link_to "Leave Review", new_therapist_review_path(therapist), class: "" %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>