config/routes.rb
Rails.application.routes.draw do
  get 'dashboard', to: "dashboard#show"
  root to: 'pages#home'
  devise_for :users
  resources :therapists, only: [:index, :show] do
    get 'update_main_therapist', to: 'therapists#update_main_therapist', as: 'assign_me'
    resources :bookings, only: [:new, :create, :edit, :update, :destroy] do
      get 'assign', to: 'pages#assign'
      get 'video_session', to: 'pages#video_session'
    end
    resources :reviews, only: [:new, :create]
  end
  resources :bookings, only: :show
  get 'sandbox', to: 'pages#sandbox'
  get 'welcome', to: 'pages#welcome'
  resources :bookings, only: :show do
    get 'video_session', to: 'pages#video_session'
  end

end

app/views/pages/assign.html.erb
<div class="assign-container container">
  <h4 class="mt-5">We hope your session went well. </h4>
  <h5>Thank you for trusting iWell.</h5>


  <div class="padded-box d-flex">
      <%= cl_image_tag @therapist.photo, class: "avatar-medium px-3 py-3" %>
    <div class="flex-item-2 d-flex flex-column justify-content-center">
      <div class="flex-wrapper">
        <h3 class= "mb-4" id="assign-heading">Would you like to leave a review for <%= @therapist.first_name %>? </h3>
        <div class="buttons-container d-flex">
          <%= link_to new_therapist_review_path(@therapist) do %>
          <div class="button-navy-small mr-3" id="yes">
            Yes
          </div>
          <% end %>
          <%= link_to dashboard_path do %>
          <div class="specialty-tag" id="no">
            No, thank you.
          </div>
          <% end %>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner">
  <h1> Online Affordable Therapy at your convenience </h1>
  <h2> No waiting lines. Connect with your licensed therapist anytime, anywhere. </h2>
  <%= link_to 'Get Started', welcome_path, :class => "button-home", :id=> "landing-cta" %>
</div>
<div class="advert-header">
 <h2 class="text-center"> How It Works </h2>
 </div>
<div class="how-it-works">
  <div class="information">
    <span class="dot"> 1 </span>
    <h2 class="text-center"><strong>Enter Info</strong></h2>
    <p class="text-center"> Enter your information to see the best suited therapists for you. </p>
  </div>
  <div class="information" id="therapist-info">
    <span class="dot"> 2 </span>
    <h2 class="text-center"><strong>Select a Therapist</strong></h2>
    <p class="text-center"> Browse through profiles and choose your therapist. </p>
  </div>
  <div class="information">
    <span class="dot"> 3 </span>
    <h2 class="text-center"><strong>Book</strong></h2>
    <p class="text-center"> Book online appointment and connect with your therapist anywhere.</p>
  </div>
</div>
<div class="therapist-container">
  <h2 class="text-center"> Our Licensed Therapists </h2>
  <div class="therapist-LP">
   <p>iWell has hundreds of licensed and experienced counselors who can help you with depression, anxiety, trauma, grief and other concerns. It takes courage to seek a more fulfilling and happier life and to take the first steps towards a change.  Our mission is to make therapy accessible and affordable to all. We are here to support you with our experienced professionals. </p>
</div>
<div class="landing-therapists">
  <div class="therapist-box">
    <div class="d-flex flex-column align-items-center"><img src="https://image.freepik.com/free-photo/business-young-woman-looking-camera-office_1301-6547.jpg" alt="Avatar" class="avatar-small">
    </div>
    <h5 class="text-center">Dr. Julia Rosch</h5>
    <h6 class="text-center">Psychologist</h6>
  </div>
  <div class="therapist-box">
     <div class="d-flex flex-column align-items-center"><img src="https://parkercollins.com/wp-content/uploads/2018/09/JH-pick_cropped-768x1024.jpg" alt="Avatar" class="avatar-small"></div>
     <h5 class="text-center"> Dr. Michael Brown</h5>
     <h6 class="text-center">Psychologist</h6>
  </div>
  <div class="therapist-box"> <div class="d-flex flex-column align-items-center"> <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTXBbPTo1SMDztdxtT809p1M5an_YoS4C97B9O3gPoKg9L74KlzQ" alt="Avatar" class="avatar-small">
  </div>
   <h5 class="text-center"> Martin Brettner</h5>
   <h6 class="text-center">Licenced Social Worker</h6>
  </div>
</div>
</div>
<div class="landing-quote">
  <p>“I never thought online counseling was  for me, but Dr. Rosch has made this experience the most beneficial  in my entire life.” – M. Schulz </p>
</div>

<div class="footer">
</div>

app/views/pages/sandbox.html.erb
<h1>This is where we build our UI kit</h1>

<head>
  <script src="https://kit.fontawesome.com/4f87db517d.js"></script>

</head>

<div class="banner">
  <div class="text-wrap">
    <h1> Affordable Online Therapy - anytime, anywhere </h1>
    <h2>No waiting lines, no time spent on commute, no extreme costs. Become a happier version of yourself, now. </h2>
  </div>
  <div class="button-navy" id="landing-cta"> Get Started
  </div> <span class="dot"></span> </div>

<img src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60" alt="Avatar" class="avatar-large">

<img src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60" alt="Avatar" class="avatar-small">


<!-- navbar -->

<nav class=<%= params[:controller] == "pages" && params[:action] == "home" ? "transparent-nav" : "normal-nav" %>>
    <a href="#" id="logo">iWell</a>
  <a href="#">Bookings</a>
  <a href="#">My Sessions</a>
</nav>

<!-- booking card -->
<div class="session-card">
  <div class="calendar">
  <!--   should display booking time  -->
    <p id="date"><%= Time.now.day %></p>
    <i class="far fa-calendar"></i>
  </div>
  <!-- if Time.now <= @booking.start_time + 24hours -->
    <% if 4+4 == 7 %>
      <div class="call">
        <i class="fas fa-video"></i>
      </div>
<!--       otherwise -->
    <% else %>
      <div class="info">
        <div class="booking-card-text">
          <h6>Your next appointment is on</h6>
          <!-- booking time to a day of the week -->
          <h4><%= Time.now.strftime("%A") %></h4>
          <i class="fas fa-video-slash"></i>
        </div>
        <div class="buttons">
          <div class="reschedule">
            Reschedule
          </div>
          <div class="cancel">
            Cancel
          </div>
        </div>
      </div>
    <% end %>
</div>

<!-- stars -->
  <div class="stars">
<!--     in all lines of code change the [therapist] variable to either therapist or @therapist, depending on what the rest of your code looks like
 -->
    <% full = [therapist].avg_rating.round(half: :down)  %>
 <% full.times do %>
    <div class="dark-star">
      <i class="fas fa-star"></i>
    </div>
    <% end %>
    <% if [therapist].avg_rating % 1 != 0 %>
    <div class="half-star">
      <i class="fas fa-star-half-alt"></i>
    </div>
    <% end %>
    <% empty = 5 - [therapist].avg_rating.round%>
    <% empty.times do %>
    <div class="light-star">
        <i class="far fa-star"></i>
    </div>
    <% end %>
  </div>

<!--   signup form  -->
<form class="sign-up">
    <h1 class="sign-up-title">Sign up </h1>
    <input type="text" class="sign-up-input" placeholder="First Name (or Nickname)" autofocus>
    <input type="email" class ="sign-up-input" placeholder="E-mail Address"
           autofocus>
    <input type="password" class="sign-up-input" placeholder="Password">
    <input type="submit" value="Sign up" class="sign-up-button">
  <p>Already have an iWell account?<a href="">Log in</a></p>
  </form>

<!--   booking form
 -->
  <form class="booking-container">
    <h1 class="booking-title">Video Call <br> 35 EUR / Hour </h1>
    <input type="text" class="booking-input" placeholder="this will change" autofocus>
    <input type="text" class ="booking-input" placeholder="this will change" autofocus>
  <div class="price-container">
  <p>Total</p>
  <h1>0 EUR (Trial Call)</h1>
  </div>
    <input type="submit" value="Book Appointment" class="booking-button">
  </form>

<div class="profile-card">
  <div class="profile-avatar-spacing">
    <img class="avatar-small" alt="avatar" src="https://kitt.lewagon.com/placeholder/users/cveneziani" />
    <p><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i> 15</p>
  </div>
  <div class="profile-description">
    <p>Dr. Julia Rosch</p>
    <p>Psychologist</p>
    <div class="profile-description-content">
      <p><strong>Specialties</strong>: anxiety, depression, stress</p>
      <p><strong>Years of experience</strong>: 5</p>
    </div>
    <p><strong>Price</strong>: 40€ per hour</p>
  </div>
</div>

<!-- bio card  -->

<div class="bio-card">
    <p><strong>Specialties</strong>: Anxiety, depression, stress</p>
    <p><strong>Years of Experience</strong>: 5</p>
    <div class="bio-description">
      <p>Hi! I am Dr. Julia Rosch, a licensed Clinical Professional Counselor (LCPC) in the state of Illinois. I earned my graduate degree in Clinical and Community Mental Health in Illinois and earned my Doctorate Degree (PhD) in General Psychology.</p>
      <p>I provide therapy services, specializing in anxiety and depression. I have experience working with individuals, couple and families.</p>
    </div>
  </div>

<!-- review card  -->

<div class="review-card">
  <h4>Reviews</h4>
  <% 4.times do %>
  <div class="review">
    <%= render 'shared/stars' %>
    <p>I had a great session with this therapist, I would highly recommend them.</p>
  </div>
<% end %>

</div>

app/views/pages/video_session.html.erb
<!-- <iframe
  src="https://tokbox.com/embed/embed/ot-embed.js?embedId=b8c20e27-37a8-477b-8799-4b3d32cccb4f&room=DEFAULT_ROOM&iframe=true"
  width="800px"
  height="640px"
  scrolling="auto"
  allow="microphone; camera"
></iframe> -->
<!-- OpenTok.js library -->
<style>
  .OT_mirrored.OT_root.OT_publisher.OT_fit-mode-cover {
  position: absolute;
  top: 150px;
  left: 20px;
}

.OT_root.OT_subscriber.OT_fit-mode-cover {
  position: relative;
  margin-top: 20px !important;
  margin-left: 300px !important;
  height: 400px !important;
  width: 600px !important;
}

#end-call {
  position: absolute;
  bottom: 100px;
  left: 45%;
}

#call-icon {
  position: absolute;
  background: red;
  color: white;
  border-radius: 50%;
  padding: 20px;
  font-size: 20px;
  position: cover;
}

</style>
<script src="https://static.opentok.com/v2/js/opentok.js"></script>
<script>

// credentials
const apiKey = '46414532';
const sessionId = '2_MX40NjQxNDUzMn5-MTU2Nzc1NzYzNTgxNX5RNEExWFJvS3EzNXVGOU80Y1UydnlmWWd-fg';
const token = 'T1==cGFydG5lcl9pZD00NjQxNDUzMiZzaWc9ZmE3NjA1MWNkYzM2OGU4MDY5YzBhNzdlNjczOWRlNDM0NjFhZTEzZjpzZXNzaW9uX2lkPTJfTVg0ME5qUXhORFV6TW41LU1UVTJOemMxTnpZek5UZ3hOWDVSTkVFeFdGSnZTM0V6TlhWR09VODBZMVV5ZG5sbVdXZC1mZyZjcmVhdGVfdGltZT0xNTY3NzU3NjYyJm5vbmNlPTAuOTgwMDEwNjAxODQ2NTI3MyZyb2xlPXB1Ymxpc2hlciZleHBpcmVfdGltZT0xNTY4MzYyNDYxJmluaXRpYWxfbGF5b3V0X2NsYXNzX2xpc3Q9';

// connect to session
const session = OT.initSession(apiKey, sessionId);

// create publisher
const publisher = OT.initPublisher();
session.connect(token, function(err) {
   // publish publisher
  session.publish(publisher);
});

// create subscriber
session.on('streamCreated', function(event) {
   session.subscribe(event.stream);
});

</script>
<%= link_to therapist_booking_assign_path do %>
<div id="end-call"><i class="fas fa-phone-slash" id="call-icon"></i></div>
<% end %>

app/views/pages/welcome.html.erb
<div class="container welcome_page-container">
    <h4 id="welcome_page-header">To show you the best professionals, please enter the following info first:</h4>
  <div class="show-page-form d-flex justify-content-center">
    <%= form_tag therapists_path, class: "show-form-container", method: :get do %>
      <% languages = [] %>
      <%  Therapist.all.each do |therapist| %>
      <% languages << therapist.language %>
      <% languages = languages.uniq %>
    <% end %>
    <div>
      <h4 class="pb-2"><strong>Language</strong></h4>
      <%= select_tag "language", options_for_select(languages.map{|s| ["#{s}", s]},:selected => params[:language]), class: "form-control" %>
        <% if params[:query].present? %>
          <%= hidden_field_tag :query, params[:query] %>
        <% end %>
        <% if params[:specialty].present? %>
          <%= hidden_field_tag :specialty, params[:specialty] %>
        <% end %>
    </div>
    <div>
      <h4 class="pb-2 pt-4"><strong>What are you struggling with?</strong></h4>
      <%= select_tag "specialty", options_from_collection_for_select(@specialties, 'name', 'name', :selected => params[:specialty]), class: "form-control" %>
        <% if params[:query].present? %>
          <%= hidden_field_tag :query, params[:query] %>
        <% end %>
        <% if params[:language].present? %>
          <%= hidden_field_tag :language, params[:language] %>
        <% end %>
    </div>
    <%= submit_tag "Show therapists", class: "button-navy mt-4 mx-0 d-flex justify-content-center", id: "welcome_page-button" %>
    <% end %>
  </div>
</div>